#!/bin/bash
HOST=$1
PORT=$2

if [ -z "$HOST" ]; then
  echo HOST cannot be blank. Good-bye!
  exit 1
fi

if [ -z "$PORT" ]; then
  echo PORT cannot be blank. Good-bye!
  exit 1
fi

while ! nc -z $HOST $PORT; do
  echo waiting for $HOST : $PORT to come up. Sleeping 5 seconds...
  sleep 5
done

echo $HOST : $PORT ready. Good-bye!
